all : Tetris

Tetris : Main.c GameStart1P.c GameStart2P.c GameStart_Network.c Server.c Client.c Result.c
	cc Main.c GameStart1P.c GameStart2P.c GameStart_Network.c Server.c Client.c Result.c -lncursesw -o Tetris
